// Code generated by protoc-gen-gin. DO NOT EDIT.
package code

func init() {
	errMap = map[int]Merror{
		ErrUserNotFound:  {code: ErrUserNotFound, msg: "用户未找到: %s"},
		ErrUserAuthFaild: {code: ErrUserAuthFaild, msg: "用户认证失败"},
	}
}
