// Code generated by protoc-gen-gin. DO NOT EDIT.

package user

import (
	gin "github.com/gin-gonic/gin"
	http "net/http"
)

type GreeterHttpServer struct {
	server GreeterServer
	router gin.IRouter
}

func RegisterGreeterServerHTTPServer(srv GreeterServer, r gin.IRouter) {
	s := GreeterHttpServer{
		server: srv,
		router: r,
	}
	s.RegisterService()
}

func (s *GreeterHttpServer) SayHello_0(c *gin.Context) {
	var in HelloRequest

	if err := c.ShouldBindQuery(&in); err != nil {
		// s.resp.ParamsError(ctx, err)
		return
	}

	in.Name = c.Params.ByName("name")

	out, err := s.server.SayHello(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GreeterHttpServer) RegisterService() {

	s.router.Handle("GET", "/helloworld/:name", s.SayHello_0)

}
